### ISSUE TITLE
원래의 증명과 비교하면서 증명하기

### ISSUE THREAD

**Issue by alxest** [vellvm/vellvm-legacy#13]
지금 원래 동작하던 정의를 수정하고 그에 맞게 증명을 수정하는 작업을 하고 있습니다.
context 없이 증명만 봐서는 이해가 힘들어서, 원래의 증명을 context 와 함께 보려고 합니다.
git 에서 수정 이전 상태로 헤드를 놓고 거기서 pg 띄워놓고 쓰고 싶습니다.
예전 상태를 가진 디렉토리를 새로 만들고, 거기서 이맥스를 새로 띄워서 쓰는 것 말고 좀 더 스마트하게 하는 방법 없을까요?

**Comment by jeehoonkang** [comment]
나 ( + @gilhur) 는 니가 말한대로 정확히 그렇게 함. . . .

**Comment by alxest** [comment]
아 질문을 잘못 올렸네요 여기가 아니구나 -_-;; 빨리 닫아야지

**Comment by alxest** [comment]
I made a mistake, I intended to make issue on other repository. Sorry for all the inconvenience.
